// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgZn-SXOT5-td6zYRHQgafMfKXP-V1ldw',
    appId: '1:734730205752:web:262836b6c8df09aabb04cd',
    messagingSenderId: '734730205752',
    projectId: 'call-app-85413',
    authDomain: 'call-app-85413.firebaseapp.com',
    storageBucket: 'call-app-85413.firebasestorage.app',
    measurementId: 'G-CMSJRLXVPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6XlouNGgAs-1nt0nCYqzgiCbpE3_1q_4',
    appId: '1:734730205752:android:bae27f6ff4ce41ebbb04cd',
    messagingSenderId: '734730205752',
    projectId: 'call-app-85413',
    storageBucket: 'call-app-85413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAd1NDOYPNIEHntvoUcZxro_8aCAev_U',
    appId: '1:734730205752:ios:b0c9346cfec796b3bb04cd',
    messagingSenderId: '734730205752',
    projectId: 'call-app-85413',
    storageBucket: 'call-app-85413.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

}